title: Vi Veri Veniversum Vivus Vici
author: Zer0
email: _placeholder_
description: > # this means to ignore newlines until "baseurl:"
  Student. Programmer. Melophile. Coffee addict. Video games enthusiast. Nature lover.
  Yield not to misfortunes. Use the hours, don’t count them.

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
